"""Update type of total in Books modal

Revision ID: 3248bd5c9d8f
Revises: 854c3d20316d
Create Date: 2023-05-08 00:03:10.231527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3248bd5c9d8f'
down_revision = '854c3d20316d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
