"""Update status_id column in Books

Revision ID: 541ad297f786
Revises: 
Create Date: 2023-05-07 22:32:30.814941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541ad297f786'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('books_ibfk_3', 'book_status', ['status_id'], ['id'])

    # ### end Alembic commands ###
