"""Add banner modal

Revision ID: 5977bd305794
Revises: 65391c0b4afb
Create Date: 2023-05-08 14:49:15.498995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5977bd305794'
down_revision = '65391c0b4afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baner', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
