"""Remove Book_status model

Revision ID: ba3cd7d151ca
Revises: a343026e3a32
Create Date: 2023-05-07 22:47:36.043272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba3cd7d151ca'
down_revision = 'a343026e3a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('update', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_status_ibfk_1'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='book_status_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
